common: &common
  adapter: postgresql
  username: jonahhalter
  password:
  min_messages: warning

development:
  <<: *common
  database: pledger_development
  host: localhost

test:
  <<: *common
  database: pledger_test
  host: localhost

production:
  <<: *common
  database: pledger_production